// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::location_report_type::LocationReport;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `location_reporter`.
///
/// Obtain a handle from the [`LocationReporterTableAccess::location_reporter`] method on [`super::RemoteTables`],
/// like `ctx.db.location_reporter()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.location_reporter().on_insert(...)`.
pub struct LocationReporterTableHandle<'ctx> {
    imp: __sdk::TableHandle<LocationReport>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `location_reporter`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LocationReporterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LocationReporterTableHandle`], which mediates access to the table `location_reporter`.
    fn location_reporter(&self) -> LocationReporterTableHandle<'_>;
}

impl LocationReporterTableAccess for super::RemoteTables {
    fn location_reporter(&self) -> LocationReporterTableHandle<'_> {
        LocationReporterTableHandle {
            imp: self.imp.get_table::<LocationReport>("location_reporter"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LocationReporterInsertCallbackId(__sdk::CallbackId);
pub struct LocationReporterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LocationReporterTableHandle<'ctx> {
    type Row = LocationReport;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LocationReport> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LocationReporterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocationReporterInsertCallbackId {
        LocationReporterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LocationReporterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LocationReporterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocationReporterDeleteCallbackId {
        LocationReporterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LocationReporterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LocationReporterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LocationReporterTableHandle<'ctx> {
    type UpdateCallbackId = LocationReporterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LocationReporterUpdateCallbackId {
        LocationReporterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LocationReporterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `location_reporter`,
/// which allows point queries on the field of the same name
/// via the [`LocationReporterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.location_reporter().id().find(...)`.
pub struct LocationReporterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LocationReport, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LocationReporterTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `location_reporter`.
    pub fn id(&self) -> LocationReporterIdUnique<'ctx> {
        LocationReporterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LocationReporterIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LocationReport> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LocationReport>("location_reporter");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LocationReport>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LocationReport>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LocationReport`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait location_reporterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LocationReport`.
    fn location_reporter(&self) -> __sdk::__query_builder::Table<LocationReport>;
}

impl location_reporterQueryTableAccess for __sdk::QueryTableAccessor {
    fn location_reporter(&self) -> __sdk::__query_builder::Table<LocationReport> {
        __sdk::__query_builder::Table::new("location_reporter")
    }
}
