// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_type::Ship;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship`.
///
/// Obtain a handle from the [`ShipTableAccess::ship`] method on [`super::RemoteTables`],
/// like `ctx.db.ship()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship().on_insert(...)`.
pub struct ShipTableHandle<'ctx> {
    imp: __sdk::TableHandle<Ship>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipTableHandle`], which mediates access to the table `ship`.
    fn ship(&self) -> ShipTableHandle<'_>;
}

impl ShipTableAccess for super::RemoteTables {
    fn ship(&self) -> ShipTableHandle<'_> {
        ShipTableHandle {
            imp: self.imp.get_table::<Ship>("ship"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipInsertCallbackId(__sdk::CallbackId);
pub struct ShipDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipTableHandle<'ctx> {
    type Row = Ship;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Ship> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipInsertCallbackId {
        ShipInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipDeleteCallbackId {
        ShipDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShipUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipTableHandle<'ctx> {
    type UpdateCallbackId = ShipUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipUpdateCallbackId {
        ShipUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ship`,
/// which allows point queries on the field of the same name
/// via the [`ShipIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship().id().find(...)`.
pub struct ShipIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Ship, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ship`.
    pub fn id(&self) -> ShipIdUnique<'ctx> {
        ShipIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Ship> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Ship>("ship");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Ship>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Ship>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Ship`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait shipQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Ship`.
    fn ship(&self) -> __sdk::__query_builder::Table<Ship>;
}

impl shipQueryTableAccess for __sdk::QueryTableAccessor {
    fn ship(&self) -> __sdk::__query_builder::Table<Ship> {
        __sdk::__query_builder::Table::new("ship")
    }
}
