// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LocationReport {
    pub id: u64,
    pub ship_mmsi: u64,
    pub lat: f64,
    pub lon: f64,
    pub cog: Option<f64>,
    pub sog: Option<f64>,
    pub timestamp: __sdk::Timestamp,
}

impl __sdk::InModule for LocationReport {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LocationReport`.
///
/// Provides typed access to columns for query building.
pub struct LocationReportCols {
    pub id: __sdk::__query_builder::Col<LocationReport, u64>,
    pub ship_mmsi: __sdk::__query_builder::Col<LocationReport, u64>,
    pub lat: __sdk::__query_builder::Col<LocationReport, f64>,
    pub lon: __sdk::__query_builder::Col<LocationReport, f64>,
    pub cog: __sdk::__query_builder::Col<LocationReport, Option<f64>>,
    pub sog: __sdk::__query_builder::Col<LocationReport, Option<f64>>,
    pub timestamp: __sdk::__query_builder::Col<LocationReport, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for LocationReport {
    type Cols = LocationReportCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LocationReportCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ship_mmsi: __sdk::__query_builder::Col::new(table_name, "ship_mmsi"),
            lat: __sdk::__query_builder::Col::new(table_name, "lat"),
            lon: __sdk::__query_builder::Col::new(table_name, "lon"),
            cog: __sdk::__query_builder::Col::new(table_name, "cog"),
            sog: __sdk::__query_builder::Col::new(table_name, "sog"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `LocationReport`.
///
/// Provides typed access to indexed columns for query building.
pub struct LocationReportIxCols {
    pub id: __sdk::__query_builder::IxCol<LocationReport, u64>,
    pub ship_mmsi: __sdk::__query_builder::IxCol<LocationReport, u64>,
    pub timestamp: __sdk::__query_builder::IxCol<LocationReport, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasIxCols for LocationReport {
    type IxCols = LocationReportIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LocationReportIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            ship_mmsi: __sdk::__query_builder::IxCol::new(table_name, "ship_mmsi"),
            timestamp: __sdk::__query_builder::IxCol::new(table_name, "timestamp"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LocationReport {}
