// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::location_report_type::LocationReport;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `location_report`.
///
/// Obtain a handle from the [`LocationReportTableAccess::location_report`] method on [`super::RemoteTables`],
/// like `ctx.db.location_report()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.location_report().on_insert(...)`.
pub struct LocationReportTableHandle<'ctx> {
    imp: __sdk::TableHandle<LocationReport>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `location_report`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LocationReportTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LocationReportTableHandle`], which mediates access to the table `location_report`.
    fn location_report(&self) -> LocationReportTableHandle<'_>;
}

impl LocationReportTableAccess for super::RemoteTables {
    fn location_report(&self) -> LocationReportTableHandle<'_> {
        LocationReportTableHandle {
            imp: self.imp.get_table::<LocationReport>("location_report"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LocationReportInsertCallbackId(__sdk::CallbackId);
pub struct LocationReportDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LocationReportTableHandle<'ctx> {
    type Row = LocationReport;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LocationReport> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LocationReportInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocationReportInsertCallbackId {
        LocationReportInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LocationReportInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LocationReportDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocationReportDeleteCallbackId {
        LocationReportDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LocationReportDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LocationReportUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LocationReportTableHandle<'ctx> {
    type UpdateCallbackId = LocationReportUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LocationReportUpdateCallbackId {
        LocationReportUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LocationReportUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `location_report`,
/// which allows point queries on the field of the same name
/// via the [`LocationReportIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.location_report().id().find(...)`.
pub struct LocationReportIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LocationReport, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LocationReportTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `location_report`.
    pub fn id(&self) -> LocationReportIdUnique<'ctx> {
        LocationReportIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LocationReportIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LocationReport> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LocationReport>("location_report");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LocationReport>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LocationReport>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LocationReport`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait location_reportQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LocationReport`.
    fn location_report(&self) -> __sdk::__query_builder::Table<LocationReport>;
}

impl location_reportQueryTableAccess for __sdk::QueryTableAccessor {
    fn location_report(&self) -> __sdk::__query_builder::Table<LocationReport> {
        __sdk::__query_builder::Table::new("location_report")
    }
}
