// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetCurrentProjectionRequestArgs {
    pub query_timestamp: __sdk::Timestamp,
    pub visibility_window_micros: i64,
}

impl From<SetCurrentProjectionRequestArgs> for super::Reducer {
    fn from(args: SetCurrentProjectionRequestArgs) -> Self {
        Self::SetCurrentProjectionRequest {
            query_timestamp: args.query_timestamp,
            visibility_window_micros: args.visibility_window_micros,
        }
    }
}

impl __sdk::InModule for SetCurrentProjectionRequestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_current_projection_request`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_current_projection_request {
    /// Request that the remote module invoke the reducer `set_current_projection_request` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_current_projection_request:set_current_projection_request_then`] to run a callback after the reducer completes.
    fn set_current_projection_request(
        &self,
        query_timestamp: __sdk::Timestamp,
        visibility_window_micros: i64,
    ) -> __sdk::Result<()> {
        self.set_current_projection_request_then(
            query_timestamp,
            visibility_window_micros,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_current_projection_request` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_current_projection_request_then(
        &self,
        query_timestamp: __sdk::Timestamp,
        visibility_window_micros: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_current_projection_request for super::RemoteReducers {
    fn set_current_projection_request_then(
        &self,
        query_timestamp: __sdk::Timestamp,
        visibility_window_micros: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetCurrentProjectionRequestArgs {
                query_timestamp,
                visibility_window_micros,
            },
            callback,
        )
    }
}
