// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::geo_point_type::GeoPoint;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StreetPoi {
    pub id: u64,
    pub osm_id: i64,
    pub name: String,
    pub highway: String,
    pub path: Vec<GeoPoint>,
    pub town_osm_id: Option<i64>,
    pub town_name: Option<String>,
    pub town_distance_m: Option<f64>,
    pub center: GeoPoint,
}

impl __sdk::InModule for StreetPoi {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StreetPoi`.
///
/// Provides typed access to columns for query building.
pub struct StreetPoiCols {
    pub id: __sdk::__query_builder::Col<StreetPoi, u64>,
    pub osm_id: __sdk::__query_builder::Col<StreetPoi, i64>,
    pub name: __sdk::__query_builder::Col<StreetPoi, String>,
    pub highway: __sdk::__query_builder::Col<StreetPoi, String>,
    pub path: __sdk::__query_builder::Col<StreetPoi, Vec<GeoPoint>>,
    pub town_osm_id: __sdk::__query_builder::Col<StreetPoi, Option<i64>>,
    pub town_name: __sdk::__query_builder::Col<StreetPoi, Option<String>>,
    pub town_distance_m: __sdk::__query_builder::Col<StreetPoi, Option<f64>>,
    pub center: __sdk::__query_builder::Col<StreetPoi, GeoPoint>,
}

impl __sdk::__query_builder::HasCols for StreetPoi {
    type Cols = StreetPoiCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StreetPoiCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            osm_id: __sdk::__query_builder::Col::new(table_name, "osm_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            highway: __sdk::__query_builder::Col::new(table_name, "highway"),
            path: __sdk::__query_builder::Col::new(table_name, "path"),
            town_osm_id: __sdk::__query_builder::Col::new(table_name, "town_osm_id"),
            town_name: __sdk::__query_builder::Col::new(table_name, "town_name"),
            town_distance_m: __sdk::__query_builder::Col::new(table_name, "town_distance_m"),
            center: __sdk::__query_builder::Col::new(table_name, "center"),
        }
    }
}

/// Indexed column accessor struct for the table `StreetPoi`.
///
/// Provides typed access to indexed columns for query building.
pub struct StreetPoiIxCols {
    pub id: __sdk::__query_builder::IxCol<StreetPoi, u64>,
    pub osm_id: __sdk::__query_builder::IxCol<StreetPoi, i64>,
}

impl __sdk::__query_builder::HasIxCols for StreetPoi {
    type IxCols = StreetPoiIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StreetPoiIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            osm_id: __sdk::__query_builder::IxCol::new(table_name, "osm_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StreetPoi {}
