// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::geo_point_type::GeoPoint;
use super::town_poi_type::TownPoi;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `town_poi`.
///
/// Obtain a handle from the [`TownPoiTableAccess::town_poi`] method on [`super::RemoteTables`],
/// like `ctx.db.town_poi()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town_poi().on_insert(...)`.
pub struct TownPoiTableHandle<'ctx> {
    imp: __sdk::TableHandle<TownPoi>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `town_poi`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TownPoiTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TownPoiTableHandle`], which mediates access to the table `town_poi`.
    fn town_poi(&self) -> TownPoiTableHandle<'_>;
}

impl TownPoiTableAccess for super::RemoteTables {
    fn town_poi(&self) -> TownPoiTableHandle<'_> {
        TownPoiTableHandle {
            imp: self.imp.get_table::<TownPoi>("town_poi"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TownPoiInsertCallbackId(__sdk::CallbackId);
pub struct TownPoiDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TownPoiTableHandle<'ctx> {
    type Row = TownPoi;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TownPoi> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TownPoiInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TownPoiInsertCallbackId {
        TownPoiInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TownPoiInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TownPoiDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TownPoiDeleteCallbackId {
        TownPoiDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TownPoiDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TownPoiUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TownPoiTableHandle<'ctx> {
    type UpdateCallbackId = TownPoiUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TownPoiUpdateCallbackId {
        TownPoiUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TownPoiUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `town_poi`,
/// which allows point queries on the field of the same name
/// via the [`TownPoiIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town_poi().id().find(...)`.
pub struct TownPoiIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TownPoi, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TownPoiTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `town_poi`.
    pub fn id(&self) -> TownPoiIdUnique<'ctx> {
        TownPoiIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TownPoiIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TownPoi> {
        self.imp.find(col_val)
    }
}

/// Access to the `osm_id` unique index on the table `town_poi`,
/// which allows point queries on the field of the same name
/// via the [`TownPoiOsmIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.town_poi().osm_id().find(...)`.
pub struct TownPoiOsmIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TownPoi, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TownPoiTableHandle<'ctx> {
    /// Get a handle on the `osm_id` unique index on the table `town_poi`.
    pub fn osm_id(&self) -> TownPoiOsmIdUnique<'ctx> {
        TownPoiOsmIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("osm_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TownPoiOsmIdUnique<'ctx> {
    /// Find the subscribed row whose `osm_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<TownPoi> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TownPoi>("town_poi");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<i64>("osm_id", |row| &row.osm_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TownPoi>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TownPoi>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TownPoi`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait town_poiQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TownPoi`.
    fn town_poi(&self) -> __sdk::__query_builder::Table<TownPoi>;
}

impl town_poiQueryTableAccess for __sdk::QueryTableAccessor {
    fn town_poi(&self) -> __sdk::__query_builder::Table<TownPoi> {
        __sdk::__query_builder::Table::new("town_poi")
    }
}
