// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::street_poi_type::StreetPoi;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateStreetArgs {
    pub street: StreetPoi,
}

impl From<UpdateStreetArgs> for super::Reducer {
    fn from(args: UpdateStreetArgs) -> Self {
        Self::UpdateStreet {
            street: args.street,
        }
    }
}

impl __sdk::InModule for UpdateStreetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_street`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_street {
    /// Request that the remote module invoke the reducer `update_street` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_street:update_street_then`] to run a callback after the reducer completes.
    fn update_street(&self, street: StreetPoi) -> __sdk::Result<()> {
        self.update_street_then(street, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_street` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_street_then(
        &self,
        street: StreetPoi,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_street for super::RemoteReducers {
    fn update_street_then(
        &self,
        street: StreetPoi,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateStreetArgs { street }, callback)
    }
}
