// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertShipStaticDataArgs {
    pub mmsi: u64,
    pub name: String,
    pub call_sign: String,
    pub destination: String,
    pub dimension_a: u16,
    pub dimension_b: u16,
    pub dimension_c: u16,
    pub dimension_d: u16,
    pub dte: bool,
    pub eta_month: u8,
    pub eta_day: u8,
    pub eta_hour: u8,
    pub eta_minute: u8,
    pub fix_type: u8,
    pub imo_number: u32,
    pub maximum_static_draught: f64,
    pub ship_type: u8,
    pub ais_version: u8,
}

impl From<UpsertShipStaticDataArgs> for super::Reducer {
    fn from(args: UpsertShipStaticDataArgs) -> Self {
        Self::UpsertShipStaticData {
            mmsi: args.mmsi,
            name: args.name,
            call_sign: args.call_sign,
            destination: args.destination,
            dimension_a: args.dimension_a,
            dimension_b: args.dimension_b,
            dimension_c: args.dimension_c,
            dimension_d: args.dimension_d,
            dte: args.dte,
            eta_month: args.eta_month,
            eta_day: args.eta_day,
            eta_hour: args.eta_hour,
            eta_minute: args.eta_minute,
            fix_type: args.fix_type,
            imo_number: args.imo_number,
            maximum_static_draught: args.maximum_static_draught,
            ship_type: args.ship_type,
            ais_version: args.ais_version,
        }
    }
}

impl __sdk::InModule for UpsertShipStaticDataArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_ship_static_data`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_ship_static_data {
    /// Request that the remote module invoke the reducer `upsert_ship_static_data` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_ship_static_data:upsert_ship_static_data_then`] to run a callback after the reducer completes.
    fn upsert_ship_static_data(
        &self,
        mmsi: u64,
        name: String,
        call_sign: String,
        destination: String,
        dimension_a: u16,
        dimension_b: u16,
        dimension_c: u16,
        dimension_d: u16,
        dte: bool,
        eta_month: u8,
        eta_day: u8,
        eta_hour: u8,
        eta_minute: u8,
        fix_type: u8,
        imo_number: u32,
        maximum_static_draught: f64,
        ship_type: u8,
        ais_version: u8,
    ) -> __sdk::Result<()> {
        self.upsert_ship_static_data_then(
            mmsi,
            name,
            call_sign,
            destination,
            dimension_a,
            dimension_b,
            dimension_c,
            dimension_d,
            dte,
            eta_month,
            eta_day,
            eta_hour,
            eta_minute,
            fix_type,
            imo_number,
            maximum_static_draught,
            ship_type,
            ais_version,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_ship_static_data` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_ship_static_data_then(
        &self,
        mmsi: u64,
        name: String,
        call_sign: String,
        destination: String,
        dimension_a: u16,
        dimension_b: u16,
        dimension_c: u16,
        dimension_d: u16,
        dte: bool,
        eta_month: u8,
        eta_day: u8,
        eta_hour: u8,
        eta_minute: u8,
        fix_type: u8,
        imo_number: u32,
        maximum_static_draught: f64,
        ship_type: u8,
        ais_version: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_ship_static_data for super::RemoteReducers {
    fn upsert_ship_static_data_then(
        &self,
        mmsi: u64,
        name: String,
        call_sign: String,
        destination: String,
        dimension_a: u16,
        dimension_b: u16,
        dimension_c: u16,
        dimension_d: u16,
        dte: bool,
        eta_month: u8,
        eta_day: u8,
        eta_hour: u8,
        eta_minute: u8,
        fix_type: u8,
        imo_number: u32,
        maximum_static_draught: f64,
        ship_type: u8,
        ais_version: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertShipStaticDataArgs {
                mmsi,
                name,
                call_sign,
                destination,
                dimension_a,
                dimension_b,
                dimension_c,
                dimension_d,
                dte,
                eta_month,
                eta_day,
                eta_hour,
                eta_minute,
                fix_type,
                imo_number,
                maximum_static_draught,
                ship_type,
                ais_version,
            },
            callback,
        )
    }
}
