// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CurrentProjectionRequest {
    pub request_id: u8,
    pub query_timestamp: __sdk::Timestamp,
    pub visibility_window_micros: i64,
}

impl __sdk::InModule for CurrentProjectionRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CurrentProjectionRequest`.
///
/// Provides typed access to columns for query building.
pub struct CurrentProjectionRequestCols {
    pub request_id: __sdk::__query_builder::Col<CurrentProjectionRequest, u8>,
    pub query_timestamp: __sdk::__query_builder::Col<CurrentProjectionRequest, __sdk::Timestamp>,
    pub visibility_window_micros: __sdk::__query_builder::Col<CurrentProjectionRequest, i64>,
}

impl __sdk::__query_builder::HasCols for CurrentProjectionRequest {
    type Cols = CurrentProjectionRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CurrentProjectionRequestCols {
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            query_timestamp: __sdk::__query_builder::Col::new(table_name, "query_timestamp"),
            visibility_window_micros: __sdk::__query_builder::Col::new(
                table_name,
                "visibility_window_micros",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `CurrentProjectionRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct CurrentProjectionRequestIxCols {
    pub request_id: __sdk::__query_builder::IxCol<CurrentProjectionRequest, u8>,
}

impl __sdk::__query_builder::HasIxCols for CurrentProjectionRequest {
    type IxCols = CurrentProjectionRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CurrentProjectionRequestIxCols {
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CurrentProjectionRequest {}
