// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum MajorAisShipType {
    NotAvailable,

    Reserved,

    WingInGround,

    Fishing,

    Towing,

    TowingLarge,

    DredgingOrUnderwaterOps,

    DivingOps,

    MilitaryOps,

    Sailing,

    PleasureCraft,

    HighSpeedCraft,

    PilotVessel,

    SearchAndRescueVessel,

    Tug,

    PortTender,

    AntiPollutionEquipment,

    LawEnforcement,

    MedicalTransport,

    NoncombatantShip,

    Passenger,

    Cargo,

    Tanker,

    Other,

    Unknown(u8),
}

impl __sdk::InModule for MajorAisShipType {
    type Module = super::RemoteModule;
}
