// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::major_ais_ship_type_type::MajorAisShipType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Ship {
    pub mmsi: u64,
    pub name: String,
    pub call_sign: Option<String>,
    pub destination: Option<String>,
    pub dimension_a: Option<u16>,
    pub dimension_b: Option<u16>,
    pub dimension_c: Option<u16>,
    pub dimension_d: Option<u16>,
    pub dte: Option<bool>,
    pub eta_month: Option<u8>,
    pub eta_day: Option<u8>,
    pub eta_hour: Option<u8>,
    pub eta_minute: Option<u8>,
    pub fix_type: Option<u8>,
    pub imo_number: Option<u32>,
    pub maximum_static_draught: Option<f64>,
    pub ship_type: Option<u8>,
    pub ais_version: Option<u8>,
    pub major_ship_type: Option<MajorAisShipType>,
}

impl __sdk::InModule for Ship {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Ship`.
///
/// Provides typed access to columns for query building.
pub struct ShipCols {
    pub mmsi: __sdk::__query_builder::Col<Ship, u64>,
    pub name: __sdk::__query_builder::Col<Ship, String>,
    pub call_sign: __sdk::__query_builder::Col<Ship, Option<String>>,
    pub destination: __sdk::__query_builder::Col<Ship, Option<String>>,
    pub dimension_a: __sdk::__query_builder::Col<Ship, Option<u16>>,
    pub dimension_b: __sdk::__query_builder::Col<Ship, Option<u16>>,
    pub dimension_c: __sdk::__query_builder::Col<Ship, Option<u16>>,
    pub dimension_d: __sdk::__query_builder::Col<Ship, Option<u16>>,
    pub dte: __sdk::__query_builder::Col<Ship, Option<bool>>,
    pub eta_month: __sdk::__query_builder::Col<Ship, Option<u8>>,
    pub eta_day: __sdk::__query_builder::Col<Ship, Option<u8>>,
    pub eta_hour: __sdk::__query_builder::Col<Ship, Option<u8>>,
    pub eta_minute: __sdk::__query_builder::Col<Ship, Option<u8>>,
    pub fix_type: __sdk::__query_builder::Col<Ship, Option<u8>>,
    pub imo_number: __sdk::__query_builder::Col<Ship, Option<u32>>,
    pub maximum_static_draught: __sdk::__query_builder::Col<Ship, Option<f64>>,
    pub ship_type: __sdk::__query_builder::Col<Ship, Option<u8>>,
    pub ais_version: __sdk::__query_builder::Col<Ship, Option<u8>>,
    pub major_ship_type: __sdk::__query_builder::Col<Ship, Option<MajorAisShipType>>,
}

impl __sdk::__query_builder::HasCols for Ship {
    type Cols = ShipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipCols {
            mmsi: __sdk::__query_builder::Col::new(table_name, "mmsi"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            call_sign: __sdk::__query_builder::Col::new(table_name, "call_sign"),
            destination: __sdk::__query_builder::Col::new(table_name, "destination"),
            dimension_a: __sdk::__query_builder::Col::new(table_name, "dimension_a"),
            dimension_b: __sdk::__query_builder::Col::new(table_name, "dimension_b"),
            dimension_c: __sdk::__query_builder::Col::new(table_name, "dimension_c"),
            dimension_d: __sdk::__query_builder::Col::new(table_name, "dimension_d"),
            dte: __sdk::__query_builder::Col::new(table_name, "dte"),
            eta_month: __sdk::__query_builder::Col::new(table_name, "eta_month"),
            eta_day: __sdk::__query_builder::Col::new(table_name, "eta_day"),
            eta_hour: __sdk::__query_builder::Col::new(table_name, "eta_hour"),
            eta_minute: __sdk::__query_builder::Col::new(table_name, "eta_minute"),
            fix_type: __sdk::__query_builder::Col::new(table_name, "fix_type"),
            imo_number: __sdk::__query_builder::Col::new(table_name, "imo_number"),
            maximum_static_draught: __sdk::__query_builder::Col::new(
                table_name,
                "maximum_static_draught",
            ),
            ship_type: __sdk::__query_builder::Col::new(table_name, "ship_type"),
            ais_version: __sdk::__query_builder::Col::new(table_name, "ais_version"),
            major_ship_type: __sdk::__query_builder::Col::new(table_name, "major_ship_type"),
        }
    }
}

/// Indexed column accessor struct for the table `Ship`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipIxCols {
    pub mmsi: __sdk::__query_builder::IxCol<Ship, u64>,
}

impl __sdk::__query_builder::HasIxCols for Ship {
    type IxCols = ShipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipIxCols {
            mmsi: __sdk::__query_builder::IxCol::new(table_name, "mmsi"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Ship {}
