// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::geo_point_type::GeoPoint;
use super::street_poi_type::StreetPoi;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `street_poi`.
///
/// Obtain a handle from the [`StreetPoiTableAccess::street_poi`] method on [`super::RemoteTables`],
/// like `ctx.db.street_poi()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.street_poi().on_insert(...)`.
pub struct StreetPoiTableHandle<'ctx> {
    imp: __sdk::TableHandle<StreetPoi>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `street_poi`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StreetPoiTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StreetPoiTableHandle`], which mediates access to the table `street_poi`.
    fn street_poi(&self) -> StreetPoiTableHandle<'_>;
}

impl StreetPoiTableAccess for super::RemoteTables {
    fn street_poi(&self) -> StreetPoiTableHandle<'_> {
        StreetPoiTableHandle {
            imp: self.imp.get_table::<StreetPoi>("street_poi"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StreetPoiInsertCallbackId(__sdk::CallbackId);
pub struct StreetPoiDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StreetPoiTableHandle<'ctx> {
    type Row = StreetPoi;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StreetPoi> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StreetPoiInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StreetPoiInsertCallbackId {
        StreetPoiInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StreetPoiInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StreetPoiDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StreetPoiDeleteCallbackId {
        StreetPoiDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StreetPoiDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StreetPoiUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StreetPoiTableHandle<'ctx> {
    type UpdateCallbackId = StreetPoiUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StreetPoiUpdateCallbackId {
        StreetPoiUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StreetPoiUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `street_poi`,
/// which allows point queries on the field of the same name
/// via the [`StreetPoiIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.street_poi().id().find(...)`.
pub struct StreetPoiIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StreetPoi, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StreetPoiTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `street_poi`.
    pub fn id(&self) -> StreetPoiIdUnique<'ctx> {
        StreetPoiIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StreetPoiIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StreetPoi> {
        self.imp.find(col_val)
    }
}

/// Access to the `osm_id` unique index on the table `street_poi`,
/// which allows point queries on the field of the same name
/// via the [`StreetPoiOsmIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.street_poi().osm_id().find(...)`.
pub struct StreetPoiOsmIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StreetPoi, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StreetPoiTableHandle<'ctx> {
    /// Get a handle on the `osm_id` unique index on the table `street_poi`.
    pub fn osm_id(&self) -> StreetPoiOsmIdUnique<'ctx> {
        StreetPoiOsmIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("osm_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StreetPoiOsmIdUnique<'ctx> {
    /// Find the subscribed row whose `osm_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<StreetPoi> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StreetPoi>("street_poi");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<i64>("osm_id", |row| &row.osm_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StreetPoi>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StreetPoi>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StreetPoi`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait street_poiQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StreetPoi`.
    fn street_poi(&self) -> __sdk::__query_builder::Table<StreetPoi>;
}

impl street_poiQueryTableAccess for __sdk::QueryTableAccessor {
    fn street_poi(&self) -> __sdk::__query_builder::Table<StreetPoi> {
        __sdk::__query_builder::Table::new("street_poi")
    }
}
