// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::geo_point_type::GeoPoint;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TownPoi {
    pub id: u64,
    pub osm_id: i64,
    pub name: String,
    pub place: String,
    pub location: GeoPoint,
}

impl __sdk::InModule for TownPoi {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TownPoi`.
///
/// Provides typed access to columns for query building.
pub struct TownPoiCols {
    pub id: __sdk::__query_builder::Col<TownPoi, u64>,
    pub osm_id: __sdk::__query_builder::Col<TownPoi, i64>,
    pub name: __sdk::__query_builder::Col<TownPoi, String>,
    pub place: __sdk::__query_builder::Col<TownPoi, String>,
    pub location: __sdk::__query_builder::Col<TownPoi, GeoPoint>,
}

impl __sdk::__query_builder::HasCols for TownPoi {
    type Cols = TownPoiCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TownPoiCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            osm_id: __sdk::__query_builder::Col::new(table_name, "osm_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            place: __sdk::__query_builder::Col::new(table_name, "place"),
            location: __sdk::__query_builder::Col::new(table_name, "location"),
        }
    }
}

/// Indexed column accessor struct for the table `TownPoi`.
///
/// Provides typed access to indexed columns for query building.
pub struct TownPoiIxCols {
    pub id: __sdk::__query_builder::IxCol<TownPoi, u64>,
    pub osm_id: __sdk::__query_builder::IxCol<TownPoi, i64>,
}

impl __sdk::__query_builder::HasIxCols for TownPoi {
    type IxCols = TownPoiIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TownPoiIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            osm_id: __sdk::__query_builder::IxCol::new(table_name, "osm_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TownPoi {}
