// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::town_poi_type::TownPoi;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateTownArgs {
    pub town: TownPoi,
}

impl From<UpdateTownArgs> for super::Reducer {
    fn from(args: UpdateTownArgs) -> Self {
        Self::UpdateTown { town: args.town }
    }
}

impl __sdk::InModule for UpdateTownArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_town`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_town {
    /// Request that the remote module invoke the reducer `update_town` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_town:update_town_then`] to run a callback after the reducer completes.
    fn update_town(&self, town: TownPoi) -> __sdk::Result<()> {
        self.update_town_then(town, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_town` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_town_then(
        &self,
        town: TownPoi,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_town for super::RemoteReducers {
    fn update_town_then(
        &self,
        town: TownPoi,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateTownArgs { town }, callback)
    }
}
