use spacetimedb::SpacetimeType;

#[derive(SpacetimeType, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MajorAisShipType {
    NotAvailable,
    Reserved,
    WingInGround,
    Fishing,
    Towing,
    TowingLarge,
    DredgingOrUnderwaterOps,
    DivingOps,
    MilitaryOps,
    Sailing,
    PleasureCraft,
    HighSpeedCraft,
    PilotVessel,
    SearchAndRescueVessel,
    Tug,
    PortTender,
    AntiPollutionEquipment,
    LawEnforcement,
    MedicalTransport,
    NoncombatantShip,
    Passenger,
    Cargo,
    Tanker,
    Other,
    Unknown(u8),
}

impl From<u8> for MajorAisShipType {
    fn from(code: u8) -> Self {
        match code {
            0 => Self::NotAvailable,
            1..=19 => Self::Reserved,
            20..=29 => Self::WingInGround,
            30 => Self::Fishing,
            31 => Self::Towing,
            32 => Self::TowingLarge,
            33 => Self::DredgingOrUnderwaterOps,
            34 => Self::DivingOps,
            35 => Self::MilitaryOps,
            36 => Self::Sailing,
            37 => Self::PleasureCraft,
            38..=39 => Self::Reserved,
            40..=49 => Self::HighSpeedCraft,
            50 => Self::PilotVessel,
            51 => Self::SearchAndRescueVessel,
            52 => Self::Tug,
            53 => Self::PortTender,
            54 => Self::AntiPollutionEquipment,
            55 => Self::LawEnforcement,
            56..=57 => Self::Reserved,
            58 => Self::MedicalTransport,
            59 => Self::NoncombatantShip,
            60..=69 => Self::Passenger,
            70..=79 => Self::Cargo,
            80..=89 => Self::Tanker,
            90..=99 => Self::Other,
            other => Self::Unknown(other),
        }
    }
}

impl MajorAisShipType {
    pub fn describe(&self) -> &'static str {
        match self {
            Self::NotAvailable => "Not available or no ship type reported",
            Self::Reserved => "Reserved AIS ship type code",
            Self::WingInGround => "Wing in ground craft or search and rescue aircraft",
            Self::Fishing => "Fishing vessel",
            Self::Towing => "Towing vessel",
            Self::TowingLarge => "Towing vessel with tow exceeding 200 meters or 25 meters breadth",
            Self::DredgingOrUnderwaterOps => "Dredging or underwater operations vessel",
            Self::DivingOps => "Diving operations vessel",
            Self::MilitaryOps => "Military operations vessel",
            Self::Sailing => "Sailing vessel",
            Self::PleasureCraft => "Pleasure craft",
            Self::HighSpeedCraft => "High-speed craft",
            Self::PilotVessel => "Pilot vessel",
            Self::SearchAndRescueVessel => "Search and rescue vessel",
            Self::Tug => "Tug",
            Self::PortTender => "Port tender",
            Self::AntiPollutionEquipment => "Anti-pollution equipment vessel",
            Self::LawEnforcement => "Law enforcement vessel",
            Self::MedicalTransport => "Medical transport vessel",
            Self::NoncombatantShip => "Noncombatant ship",
            Self::Passenger => "Passenger vessel",
            Self::Cargo => "Cargo vessel",
            Self::Tanker => "Tanker",
            Self::Other => "Other ship or cargo type",
            Self::Unknown(_) => "Unknown AIS ship type code",
        }
    }

    pub fn short_description(&self) -> &'static str {
        match self {
            Self::NotAvailable => "Not available",
            Self::Reserved => "Reserved",
            Self::WingInGround => "WIG / SAR aircraft",
            Self::Fishing => "Fishing",
            Self::Towing => "Towing",
            Self::TowingLarge => "Large tow",
            Self::DredgingOrUnderwaterOps => "Dredging / underwater ops",
            Self::DivingOps => "Diving ops",
            Self::MilitaryOps => "Military ops",
            Self::Sailing => "Sailing",
            Self::PleasureCraft => "Pleasure craft",
            Self::HighSpeedCraft => "High-speed craft",
            Self::PilotVessel => "Pilot vessel",
            Self::SearchAndRescueVessel => "SAR vessel",
            Self::Tug => "Tug",
            Self::PortTender => "Port tender",
            Self::AntiPollutionEquipment => "Anti-pollution",
            Self::LawEnforcement => "Law enforcement",
            Self::MedicalTransport => "Medical transport",
            Self::NoncombatantShip => "Noncombatant",
            Self::Passenger => "Passenger",
            Self::Cargo => "Cargo",
            Self::Tanker => "Tanker",
            Self::Other => "Other",
            Self::Unknown(_) => "Unknown",
        }
    }
}
