// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::current_ship_projection_type::CurrentShipProjection;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `current_ship_projection`.
///
/// Obtain a handle from the [`CurrentShipProjectionTableAccess::current_ship_projection`] method on [`super::RemoteTables`],
/// like `ctx.db.current_ship_projection()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.current_ship_projection().on_insert(...)`.
pub struct CurrentShipProjectionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CurrentShipProjection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `current_ship_projection`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CurrentShipProjectionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CurrentShipProjectionTableHandle`], which mediates access to the table `current_ship_projection`.
    fn current_ship_projection(&self) -> CurrentShipProjectionTableHandle<'_>;
}

impl CurrentShipProjectionTableAccess for super::RemoteTables {
    fn current_ship_projection(&self) -> CurrentShipProjectionTableHandle<'_> {
        CurrentShipProjectionTableHandle {
            imp: self
                .imp
                .get_table::<CurrentShipProjection>("current_ship_projection"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CurrentShipProjectionInsertCallbackId(__sdk::CallbackId);
pub struct CurrentShipProjectionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CurrentShipProjectionTableHandle<'ctx> {
    type Row = CurrentShipProjection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CurrentShipProjection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CurrentShipProjectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CurrentShipProjectionInsertCallbackId {
        CurrentShipProjectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CurrentShipProjectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CurrentShipProjectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CurrentShipProjectionDeleteCallbackId {
        CurrentShipProjectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CurrentShipProjectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CurrentShipProjection>("current_ship_projection");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CurrentShipProjection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CurrentShipProjection>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CurrentShipProjection`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait current_ship_projectionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CurrentShipProjection`.
    fn current_ship_projection(&self) -> __sdk::__query_builder::Table<CurrentShipProjection>;
}

impl current_ship_projectionQueryTableAccess for __sdk::QueryTableAccessor {
    fn current_ship_projection(&self) -> __sdk::__query_builder::Table<CurrentShipProjection> {
        __sdk::__query_builder::Table::new("current_ship_projection")
    }
}
