// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ProjectShipLocationsArgs {
    pub query_timestamp: __sdk::Timestamp,
    pub visibility_window_micros: i64,
}

impl From<ProjectShipLocationsArgs> for super::Reducer {
    fn from(args: ProjectShipLocationsArgs) -> Self {
        Self::ProjectShipLocations {
            query_timestamp: args.query_timestamp,
            visibility_window_micros: args.visibility_window_micros,
        }
    }
}

impl __sdk::InModule for ProjectShipLocationsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `project_ship_locations`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait project_ship_locations {
    /// Request that the remote module invoke the reducer `project_ship_locations` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`project_ship_locations:project_ship_locations_then`] to run a callback after the reducer completes.
    fn project_ship_locations(
        &self,
        query_timestamp: __sdk::Timestamp,
        visibility_window_micros: i64,
    ) -> __sdk::Result<()> {
        self.project_ship_locations_then(query_timestamp, visibility_window_micros, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `project_ship_locations` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn project_ship_locations_then(
        &self,
        query_timestamp: __sdk::Timestamp,
        visibility_window_micros: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl project_ship_locations for super::RemoteReducers {
    fn project_ship_locations_then(
        &self,
        query_timestamp: __sdk::Timestamp,
        visibility_window_micros: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ProjectShipLocationsArgs {
                query_timestamp,
                visibility_window_micros,
            },
            callback,
        )
    }
}
