// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Ship {
    pub id: u64,
    pub name: String,
    pub call_sign: Option<String>,
}

impl __sdk::InModule for Ship {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Ship`.
///
/// Provides typed access to columns for query building.
pub struct ShipCols {
    pub id: __sdk::__query_builder::Col<Ship, u64>,
    pub name: __sdk::__query_builder::Col<Ship, String>,
    pub call_sign: __sdk::__query_builder::Col<Ship, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Ship {
    type Cols = ShipCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            call_sign: __sdk::__query_builder::Col::new(table_name, "call_sign"),
        }
    }
}

/// Indexed column accessor struct for the table `Ship`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipIxCols {
    pub id: __sdk::__query_builder::IxCol<Ship, u64>,
}

impl __sdk::__query_builder::HasIxCols for Ship {
    type IxCols = ShipIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Ship {}
