// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddLocationReportArgs {
    pub ship_id: u64,
    pub lat: f64,
    pub lon: f64,
    pub cog: Option<f64>,
    pub sog: Option<f64>,
}

impl From<AddLocationReportArgs> for super::Reducer {
    fn from(args: AddLocationReportArgs) -> Self {
        Self::AddLocationReport {
            ship_id: args.ship_id,
            lat: args.lat,
            lon: args.lon,
            cog: args.cog,
            sog: args.sog,
        }
    }
}

impl __sdk::InModule for AddLocationReportArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_location_report`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_location_report {
    /// Request that the remote module invoke the reducer `add_location_report` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_location_report:add_location_report_then`] to run a callback after the reducer completes.
    fn add_location_report(
        &self,
        ship_id: u64,
        lat: f64,
        lon: f64,
        cog: Option<f64>,
        sog: Option<f64>,
    ) -> __sdk::Result<()> {
        self.add_location_report_then(ship_id, lat, lon, cog, sog, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_location_report` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_location_report_then(
        &self,
        ship_id: u64,
        lat: f64,
        lon: f64,
        cog: Option<f64>,
        sog: Option<f64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_location_report for super::RemoteReducers {
    fn add_location_report_then(
        &self,
        ship_id: u64,
        lat: f64,
        lon: f64,
        cog: Option<f64>,
        sog: Option<f64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddLocationReportArgs {
                ship_id,
                lat,
                lon,
                cog,
                sog,
            },
            callback,
        )
    }
}
