// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CurrentShipProjection {
    pub ship_mmsi: u64,
    pub query_timestamp: __sdk::Timestamp,
    pub lat: f64,
    pub lon: f64,
    pub cog: Option<f64>,
    pub sog: Option<f64>,
    pub before_timestamp: __sdk::Timestamp,
    pub after_timestamp: Option<__sdk::Timestamp>,
    pub used_dead_reckoning: bool,
}

impl __sdk::InModule for CurrentShipProjection {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CurrentShipProjection`.
///
/// Provides typed access to columns for query building.
pub struct CurrentShipProjectionCols {
    pub ship_mmsi: __sdk::__query_builder::Col<CurrentShipProjection, u64>,
    pub query_timestamp: __sdk::__query_builder::Col<CurrentShipProjection, __sdk::Timestamp>,
    pub lat: __sdk::__query_builder::Col<CurrentShipProjection, f64>,
    pub lon: __sdk::__query_builder::Col<CurrentShipProjection, f64>,
    pub cog: __sdk::__query_builder::Col<CurrentShipProjection, Option<f64>>,
    pub sog: __sdk::__query_builder::Col<CurrentShipProjection, Option<f64>>,
    pub before_timestamp: __sdk::__query_builder::Col<CurrentShipProjection, __sdk::Timestamp>,
    pub after_timestamp:
        __sdk::__query_builder::Col<CurrentShipProjection, Option<__sdk::Timestamp>>,
    pub used_dead_reckoning: __sdk::__query_builder::Col<CurrentShipProjection, bool>,
}

impl __sdk::__query_builder::HasCols for CurrentShipProjection {
    type Cols = CurrentShipProjectionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CurrentShipProjectionCols {
            ship_mmsi: __sdk::__query_builder::Col::new(table_name, "ship_mmsi"),
            query_timestamp: __sdk::__query_builder::Col::new(table_name, "query_timestamp"),
            lat: __sdk::__query_builder::Col::new(table_name, "lat"),
            lon: __sdk::__query_builder::Col::new(table_name, "lon"),
            cog: __sdk::__query_builder::Col::new(table_name, "cog"),
            sog: __sdk::__query_builder::Col::new(table_name, "sog"),
            before_timestamp: __sdk::__query_builder::Col::new(table_name, "before_timestamp"),
            after_timestamp: __sdk::__query_builder::Col::new(table_name, "after_timestamp"),
            used_dead_reckoning: __sdk::__query_builder::Col::new(
                table_name,
                "used_dead_reckoning",
            ),
        }
    }
}
