// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::oldest_location_report_time_type::OldestLocationReportTime;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `oldest_location_report_time`.
///
/// Obtain a handle from the [`OldestLocationReportTimeTableAccess::oldest_location_report_time`] method on [`super::RemoteTables`],
/// like `ctx.db.oldest_location_report_time()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.oldest_location_report_time().on_insert(...)`.
pub struct OldestLocationReportTimeTableHandle<'ctx> {
    imp: __sdk::TableHandle<OldestLocationReportTime>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `oldest_location_report_time`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OldestLocationReportTimeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OldestLocationReportTimeTableHandle`], which mediates access to the table `oldest_location_report_time`.
    fn oldest_location_report_time(&self) -> OldestLocationReportTimeTableHandle<'_>;
}

impl OldestLocationReportTimeTableAccess for super::RemoteTables {
    fn oldest_location_report_time(&self) -> OldestLocationReportTimeTableHandle<'_> {
        OldestLocationReportTimeTableHandle {
            imp: self
                .imp
                .get_table::<OldestLocationReportTime>("oldest_location_report_time"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OldestLocationReportTimeInsertCallbackId(__sdk::CallbackId);
pub struct OldestLocationReportTimeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for OldestLocationReportTimeTableHandle<'ctx> {
    type Row = OldestLocationReportTime;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OldestLocationReportTime> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OldestLocationReportTimeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OldestLocationReportTimeInsertCallbackId {
        OldestLocationReportTimeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OldestLocationReportTimeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OldestLocationReportTimeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OldestLocationReportTimeDeleteCallbackId {
        OldestLocationReportTimeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OldestLocationReportTimeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<OldestLocationReportTime>("oldest_location_report_time");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OldestLocationReportTime>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OldestLocationReportTime>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OldestLocationReportTime`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait oldest_location_report_timeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OldestLocationReportTime`.
    fn oldest_location_report_time(
        &self,
    ) -> __sdk::__query_builder::Table<OldestLocationReportTime>;
}

impl oldest_location_report_timeQueryTableAccess for __sdk::QueryTableAccessor {
    fn oldest_location_report_time(
        &self,
    ) -> __sdk::__query_builder::Table<OldestLocationReportTime> {
        __sdk::__query_builder::Table::new("oldest_location_report_time")
    }
}
