// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ship_projection_type::ShipProjection;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ship_projection`.
///
/// Obtain a handle from the [`ShipProjectionTableAccess::ship_projection`] method on [`super::RemoteTables`],
/// like `ctx.db.ship_projection()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_projection().on_insert(...)`.
pub struct ShipProjectionTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShipProjection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ship_projection`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShipProjectionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShipProjectionTableHandle`], which mediates access to the table `ship_projection`.
    fn ship_projection(&self) -> ShipProjectionTableHandle<'_>;
}

impl ShipProjectionTableAccess for super::RemoteTables {
    fn ship_projection(&self) -> ShipProjectionTableHandle<'_> {
        ShipProjectionTableHandle {
            imp: self.imp.get_table::<ShipProjection>("ship_projection"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShipProjectionInsertCallbackId(__sdk::CallbackId);
pub struct ShipProjectionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShipProjectionTableHandle<'ctx> {
    type Row = ShipProjection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ShipProjection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ShipProjectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipProjectionInsertCallbackId {
        ShipProjectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShipProjectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShipProjectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShipProjectionDeleteCallbackId {
        ShipProjectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShipProjectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShipProjectionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShipProjectionTableHandle<'ctx> {
    type UpdateCallbackId = ShipProjectionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShipProjectionUpdateCallbackId {
        ShipProjectionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShipProjectionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `ship_id` unique index on the table `ship_projection`,
/// which allows point queries on the field of the same name
/// via the [`ShipProjectionShipIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ship_projection().ship_id().find(...)`.
pub struct ShipProjectionShipIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ShipProjection, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ShipProjectionTableHandle<'ctx> {
    /// Get a handle on the `ship_id` unique index on the table `ship_projection`.
    pub fn ship_id(&self) -> ShipProjectionShipIdUnique<'ctx> {
        ShipProjectionShipIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("ship_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ShipProjectionShipIdUnique<'ctx> {
    /// Find the subscribed row whose `ship_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ShipProjection> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ShipProjection>("ship_projection");
    _table.add_unique_constraint::<u64>("ship_id", |row| &row.ship_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShipProjection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ShipProjection>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ShipProjection`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ship_projectionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ShipProjection`.
    fn ship_projection(&self) -> __sdk::__query_builder::Table<ShipProjection>;
}

impl ship_projectionQueryTableAccess for __sdk::QueryTableAccessor {
    fn ship_projection(&self) -> __sdk::__query_builder::Table<ShipProjection> {
        __sdk::__query_builder::Table::new("ship_projection")
    }
}
