// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShipProjection {
    pub ship_mmsi: u64,
    pub query_timestamp: __sdk::Timestamp,
    pub lat: f64,
    pub lon: f64,
    pub cog: Option<f64>,
    pub sog: Option<f64>,
    pub before_timestamp: __sdk::Timestamp,
    pub after_timestamp: Option<__sdk::Timestamp>,
    pub used_dead_reckoning: bool,
}

impl __sdk::InModule for ShipProjection {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ShipProjection`.
///
/// Provides typed access to columns for query building.
pub struct ShipProjectionCols {
    pub ship_mmsi: __sdk::__query_builder::Col<ShipProjection, u64>,
    pub query_timestamp: __sdk::__query_builder::Col<ShipProjection, __sdk::Timestamp>,
    pub lat: __sdk::__query_builder::Col<ShipProjection, f64>,
    pub lon: __sdk::__query_builder::Col<ShipProjection, f64>,
    pub cog: __sdk::__query_builder::Col<ShipProjection, Option<f64>>,
    pub sog: __sdk::__query_builder::Col<ShipProjection, Option<f64>>,
    pub before_timestamp: __sdk::__query_builder::Col<ShipProjection, __sdk::Timestamp>,
    pub after_timestamp: __sdk::__query_builder::Col<ShipProjection, Option<__sdk::Timestamp>>,
    pub used_dead_reckoning: __sdk::__query_builder::Col<ShipProjection, bool>,
}

impl __sdk::__query_builder::HasCols for ShipProjection {
    type Cols = ShipProjectionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShipProjectionCols {
            ship_mmsi: __sdk::__query_builder::Col::new(table_name, "ship_mmsi"),
            query_timestamp: __sdk::__query_builder::Col::new(table_name, "query_timestamp"),
            lat: __sdk::__query_builder::Col::new(table_name, "lat"),
            lon: __sdk::__query_builder::Col::new(table_name, "lon"),
            cog: __sdk::__query_builder::Col::new(table_name, "cog"),
            sog: __sdk::__query_builder::Col::new(table_name, "sog"),
            before_timestamp: __sdk::__query_builder::Col::new(table_name, "before_timestamp"),
            after_timestamp: __sdk::__query_builder::Col::new(table_name, "after_timestamp"),
            used_dead_reckoning: __sdk::__query_builder::Col::new(
                table_name,
                "used_dead_reckoning",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `ShipProjection`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShipProjectionIxCols {
    pub ship_mmsi: __sdk::__query_builder::IxCol<ShipProjection, u64>,
}

impl __sdk::__query_builder::HasIxCols for ShipProjection {
    type IxCols = ShipProjectionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShipProjectionIxCols {
            ship_mmsi: __sdk::__query_builder::IxCol::new(table_name, "ship_mmsi"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShipProjection {}
